#!/bin/bash

set -e

REPO_COMMIT_SHORT=$(echo "$ALIGN_PDK_SKY130_REPO_COMMIT" | cut -c 1-7)

mkdir -p "$TOOLS"
git clone "$ALIGN_PDK_SKY130_REPO_URL" "${TOOLS}/$ALIGN_PDK_SKY130_NAME"
cd "${TOOLS}/$ALIGN_PDK_SKY130_NAME"
git checkout "$ALIGN_PDK_SKY130_REPO_COMMIT"
