FROM glud/xyce:parallel

RUN yum install -y perl numpy scipy

ENV XYCE_SRCDIR=/opt/Xyce/
ENV XYCE_OUTDIR=/usr/local/
WORKDIR $XYCE_SRCDIR

COPY ./xyce-tests-parallel.sh ./xyce-build/xyce-tests.sh

ENV XYCE_VERSION=6.7
RUN curl https://xyce.sandia.gov/downloads/_assets/documents/Xyce_Regression-${XYCE_VERSION}.tar.gz | tar xz && mv Xyce_Regression-${XYCE_VERSION} Xyce_Regression
